/*
 * Copyright 2018 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.mobilehelptosave.domain

import com.eclipsesource.schema.SchemaType
import org.joda.time.{LocalDate, YearMonth}
import org.scalatest.{Matchers, WordSpec}
import play.api.libs.json.{JsBoolean, JsObject, JsValue, Json}
import uk.gov.hmrc.mobilehelptosave.io.Resources
import uk.gov.hmrc.mobilehelptosave.scalatest.SchemaMatchers

class AccountJsonSpec extends WordSpec with Matchers with SchemaMatchers {

  private val ramlAccountSchema =
    banAdditionalProperties(loadResourceJson("/public/api/conf/1.0/schemas/account.json"))
      .as[SchemaType]

  private val testAccount = Account(
    openedYearMonth = new YearMonth(2018, 5),
    isClosed = false,
    Blocking(false),
    BigDecimal("543.12"),
    0, 0, 0,
    thisMonthEndDate = new LocalDate(2020, 12, 31),
    bonusTerms = Seq(
      BonusTerm(bonusEstimate = BigDecimal("200.12"), bonusPaid = BigDecimal("200.12"), endDate = new LocalDate(2020, 4, 30), bonusPaidOnOrAfterDate = new LocalDate(2020, 5, 1)),
      BonusTerm(bonusEstimate = BigDecimal("71.44"), bonusPaid = 0, endDate = new LocalDate(2022, 4, 30), bonusPaidOnOrAfterDate = new LocalDate(2022, 5, 1))
    ))

  "Account JSON" when {
    "account is in happy path state" should {
      "be a valid instance of the schema used in the RAML" in {
        Json.toJson(testAccount) should validateAgainstSchema(ramlAccountSchema)
      }
    }

    "account is blocked" should {
      "be a valid instance of the schema used in the RAML" in {
        val blockedAccount = testAccount.copy(blocked = Blocking(true))
        Json.toJson(blockedAccount) should validateAgainstSchema(ramlAccountSchema)
      }
    }

    "account is closed" should {
      "be a valid instance of the schema used in the RAML" in {
        val closedAccount = testAccount.copy(
          isClosed = true,
          closureDate = Some(new LocalDate(2020, 11, 5)),
          closingBalance = Some(BigDecimal("543.12")),
          balance = 0,
          bonusTerms = Seq(
            testAccount.bonusTerms.head,
            testAccount.bonusTerms(1).copy(bonusEstimate = 0)
          )
        )
        Json.toJson(closedAccount) should validateAgainstSchema(ramlAccountSchema)
      }
    }
  }

  private def loadResourceJson(resourceName: String): JsValue =
    Resources.withResource(resourceName, getClass)(Json.parse)

  /**
    * Transforms a JSON schema by recursively adding "additionalProperties": false to every object.
    *
    * The reason we do this in this test code instead of just adding
    * "additionalProperties": false to the schema file is because we want
    * this test to detect fields generated by the code that aren't in the
    * schema because that could indicate that we have given a field a
    * different name in the code from the schema BUT we don't want to commit
    * to consumers of the API that we will never add any fields.
    */
  private def banAdditionalProperties(schema: JsValue): JsValue = {
    val augmented: JsValue = schema match {
      case o@JsObject(_) if (schema \ "type").asOpt[String].contains("object") =>
        o + ("additionalProperties" -> JsBoolean(false))
      case v => v
    }

    augmented match {
      case o@JsObject(_) =>
        JsObject(o.fields.map { case (k, v) => (k, banAdditionalProperties(v)) })
      case v => v
    }
  }

}
