#%RAML 1.0
title: Help To Save
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

types:
  nino:
    type: string
    example: AA999999A

traits:
  loginRequired:
    responses:
      401:
        body:
          application/json:
            type: types.errorResponse
            examples:
              invalidCredentials:
                description: Invalid Authentication information provided.
                value:
                  code: INVALID_CREDENTIALS

  permissionOnAccountNinoRequired:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              noPermissionOnAccountNino:
                description: The logged in user is not permitted to access the Help to Save Savings Account for the specified NINO.
                value:
                  code: NO_PERMISSION_ON_ACCOUNT_NINO

  ninoInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ninoInvalid:
                description: Invalid NINO (incorrect format)
                value:
                  code: NINO_INVALID

  # We implement our own shuttering instead of using the API platform shuttering (<confluence>/display/DTRG/How+to+emergency+shutter+an+API)
  # because:
  # 1) The response returned when API platform shuttering is used (503 with code: "SERVER_ERROR") is difficult to distinguish from the response when certain errors occur.
  # 2) API platform shuttering does not support custom error messages
  #
  # Note that api-documentation-frontend doesn't display anything for this
  # trait, probably because it goes outside API platform norms (errors are
  # usually specified using types.errorResponse, like in ninoInvalid above,
  # but we have more fields in this error response than there are in the API
  # platform standard error response so we can't use types.errorResponse).
  mobileHelpToSaveShuttered:
    responses:
      503:
        body:
          application/json:
            type: !include schemas/shuttering.json
            example: !include examples/shuttering.json

/individuals/mobile-help-to-save/savings-account/{nino}:
  uriParameters:
    nino:
      description: Savings account holder's National Insurance Number
      type: string
      example: AA000003D
#  is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, ninoInvalid, mobileHelpToSaveShuttered]
#  uriParameters:
#    nino:
#      type: nino
#      description: The account holder's national insurance number
#  get:
#    displayName: Get account information
#    responses:
#      200:
#        body:
#          application/json:
#            type: !include schemas/account.json
#            example: !include examples/account.json
  /transactions:
    is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, ninoInvalid, mobileHelpToSaveShuttered]
    get:
      displayName: Get transactions
      description: Retrieve the details of the transaction activity that has taken place on the HTS Account associated with the NINO provided. All movements on the account across all terms will be returned.
      (annotations.scope): "read:help-to-save"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:help-to-save" ] } ]
      responses:
        200:
          body:
            application/json:
              type: !include schemas/transactions.json
              example: !include examples/transactions.json

#  /messages:
#    is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, blocked]
#    get:
#      displayName: Get message list
#    /{messageId}:
#      is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, blocked]
#      get:
#        displayName: Get message
