#%RAML 1.0
title: Help To Save
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

types:
  nino:
    type: string
    example: AA999999A

traits:
  loginRequired:
    responses:
      401:
        body:
          application/json:
            type: types.errorResponse
            examples:
              invalidCredentials:
                description: Invalid Authentication information provided.
                value:
                  code: INVALID_CREDENTIALS

  permissionOnAccountNinoRequired:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              noPermissionOnAccountNino:
                description: The logged in user is not permitted to access the Help to Save Savings Account for the specified NINO.
                value:
                  code: NO_PERMISSION_ON_ACCOUNT_NINO

  ninoInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ninoInvalid:
                description: Invalid NINO (incorrect format)
                value:
                  code: NINO_INVALID

  # We implement our own shuttering instead of using the API platform shuttering (<confluence>/display/DTRG/How+to+emergency+shutter+an+API)
  # because:
  # 1) The response returned when API platform shuttering is used (503 with code: "SERVER_ERROR") is difficult to distinguish from the response when certain errors occur.
  # 2) API platform shuttering does not support custom error messages
  #
  # Note that api-documentation-frontend doesn't display anything for this
  # trait, probably because it goes outside API platform norms (errors are
  # usually specified using types.errorResponse, like in ninoInvalid above,
  # but we have more fields in this error response than there are in the API
  # platform standard error response so we can't use types.errorResponse).
  mobileHelpToSaveShuttered:
    responses:
      # we'd rather use 503 instead of 521 but can't use 503 because the API platform nginx discards any bodies in 503 responses returned by microservices - see NGC-3396
      521:
        body:
          application/json:
            type: !include schemas/shuttering.json
            example: !include examples/shuttering.json

/individuals/mobile-help-to-save/savings-account/{nino}:
  uriParameters:
    nino:
      description: Savings account holder's National Insurance Number
      type: string
      example: AA000003D
  is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, ninoInvalid, mobileHelpToSaveShuttered]
  get:
    displayName: Get account information
    description: Retrieves the details of the Help to Save account
    (annotations.scope): "read:native-apps-api-orchestration"
    securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
    responses:
      200:
        body:
          application/json:
            type: !include schemas/account.json
            example: !include examples/account.json
      404:
        body:
          application/json:
            type: types.errorResponse
            example: !include examples/accountNotFound.json

  /transactions:
    is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, ninoInvalid, mobileHelpToSaveShuttered]
    get:
      displayName: Get transactions
      description: Retrieve the details of the transaction activity that has taken place on the HTS Account associated with the NINO provided. All movements on the account across all terms will be returned. Transactions will be returned in the reverse of the order they were applied to the account (i.e. newest first).
      (annotations.scope): "read:native-apps-api-orchestration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
      responses:
        200:
          body:
            application/json:
              type: !include schemas/transactions.json
              example: !include examples/transactions.json

  /goals/current-goal:
     is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, ninoInvalid, mobileHelpToSaveShuttered]
     put:
       body:
         application/json:
           type: !include schemas/goal.json
           example: !include examples/goal.json
       displayName: Set a savings goal for the user
       description: Set a savings goal for the user. This will replace any existing savings goal. The goal must be between £1 and £50 (or the whatever the remaining monthly savings headroom might be) and not contain any fractional pence values (e.g. £1.234)
       (annotations.scope): "read:native-apps-api-orchestration"
       securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
       responses:
         204:
         422:
           body:
             properties:
               error:
             example:
               error: goal amount should be in range 1 to 50
     delete:
       displayName: Remove the users' current savings goal
       description: Remove the users' current savings goal
       (annotations.scope): "read:native-apps-api-orchestration"
       securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
       responses:
         204:

  /milestones:
    is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, ninoInvalid, mobileHelpToSaveShuttered]
    get:
      displayName: Get milestones
      description: Retrieves key milestones about a user account, there can only be one milestone per milestone type at any one time and milestones marked as seen will not be retrieved
      (annotations.scope): "read:native-apps-api-orchestration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
      responses:
        200:
          body:
            application/json:
              type: !include schemas/milestones.json
              example: !include examples/milestones.json

  /milestones/{milestoneId}/seen:
     is: [headers.acceptHeader, loginRequired, permissionOnAccountNinoRequired, ninoInvalid, mobileHelpToSaveShuttered]
     put:
       displayName: Mark milestone as a seen
       description: Marks a milestone as seen by the user, meaning it will not be retrieved in the future
       (annotations.scope): "read:native-apps-api-orchestration"
       securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
       responses:
         204: